#!/bin/bash
#PBS -l walltime=999:00:00,mem=20gb
#PBS -l nodes=1:ppn=20
#PBS -d .


python svm-pipe-part1.iter.py /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/positive.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/negative.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/treshold.1_100.table 1 100
python svm-pipe-part1.iter.py /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/positive.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/negative.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/treshold.1_1000.table 1 1000
python svm-pipe-part1.iter.py /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/positive.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/negative.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/treshold.1_10000.table 1 10000



