#!/bin/bash
#PBS -l walltime=999:00:00,mem=20gb
#PBS -l nodes=1:ppn=20
#PBS -d .


python svm-pipe-part1.c.py /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/positive.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/negative.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/treshold.10.table 10
python svm-pipe-part1.c.py /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/positive.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/negative.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/treshold.100.table 100
python svm-pipe-part1.c.py /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/positive.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/negative.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/treshold.1000.table 1000
python svm-pipe-part1.c.py /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/positive.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/negative.expressionCodonFreq.predictions /mnt/lustre/kasianov/Projects/ArabFagop/newProtocol/diffTresholds/results_treshold_18/predictions/treshold.10000.table 10000



